# name: Continuous Delivery

# on:
#   workflow_run:
#     workflows:
#       - "Continuous Integration"
#     type:
#       - complete
# jobs:
#   run-docker-container:
#     name: Run container
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download image
#         uses: ishworkh/docker-image-artifact-download@v1
#         with:
#           image: "go-app:latest"
#       - name: Build
#         run:  make start
#       - name: Build
#         run:  docker ps -a
