name: Build & Test

on:
  workflow_call:
  # TODO add secret
  # TODO add input params

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Check Golang version
        run: go version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: make test

  build:
    name: Build artifact
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build
      run:  make build
    - name: Push
      run:  make push
