name: Continuous Integration

on:
  pull_request:
    paths-ignore:
    - README.md
    - .gitignore
    - pull_request_template.md

  push: 
   branches:
     - "**"
          
jobs:
  build-test:
    name: Build & Unit Test
    uses: ./.github/workflows/ci.yml
