name: Pull, Tag & Push a container

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: The environment to deploy to e.g. dev/prod etc. Must correspond to a configured github environment.
        required: true
      release-tag:
        type: string
        description: The service tag to deploy e.g. post/author/all etc.
        required: true
      git-hash:
        type: string
        description: The full Git SHA to use to pull from ECR.
        required: true
    secrets:
      GITHUBACTIONSTOKEN:
        required: true 

jobs:
  pull-tag-push:
    name: Pull, Tag & Push a container
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read    
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.git-hash }}

      - name: Config GIT to install packages via HTTPS OAuth instead of HTTPS 
        run:  |
          git config --global url."https://${{ env.PAT_TOKEN }}:x-oauth-basic@github.com/businessinsider".insteadOf "https://github.com/businessinsider"
          go env -w "GOPRIVATE=github.com/businessinsider/*"
          pwd
        working-directory: ./

      - name: Config GIT to install packages via HTTPS OAuth instead of SSH 
        run: |
          git config --global url."https://${{ env.PAT_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
          pwd

      - name: Build
        run:  make build

      - name: Logs setup if failure
        if: failure()
        run: make integ-logs

      - name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      
      - name: Set short git commit SHA
        id: get-short-hash
        run: |
          shortHash=$(git rev-parse --short ${{ inputs.git-hash }})
          echo "short_hash=$shortHash" >> $GITHUB_OUTPUT          

      - name: Confirm git commit SHA output
        run: echo ${{ steps.get-short-hash.outputs.short_hash }}

      - name: Get version tag
        id: get-version
        run: echo "version_tag=$(make version)" >> $GITHUB_OUTPUT

      - name: Confirm version tag output
        run: echo ${{ steps.get-version.outputs.version_tag }}

      - name: Output inputs
        run: |
          echo ${{ inputs.environment }}
          echo ${{ inputs.release-tag }}

      - name: Push all services
        if: contains(inputs.release-tag, 'all')
        env:
          SHORTHASH: ${{ steps.get-short-hash.outputs.short_hash }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          make push SERVICE_TAG=author
          make push SERVICE_TAG=category
          make push SERVICE_TAG=homepage
          make push SERVICE_TAG=post
          make push SERVICE_TAG=product
          make push SERVICE_TAG=publication
          make push SERVICE_TAG=sponsor
          make push SERVICE_TAG=vertical

      - name: Push Test service
        if: contains(inputs.release-tag, 'test')
        env:
          SHORTHASH: ${{ steps.get-short-hash.outputs.short_hash }}
          ENVIRONMENT: ${{ inputs.environment }}
          SERVICE_TAG: test
        run: make push
